services:
  csgo-bot:
    build: .
    container_name: csgo-bot
    image: tom/csgo-bot
    restart: on-failure
    volumes:
      - ./db/profiles_prod.sqlite3:/app/db/profiles_prod.sqlite3
      - ./db/profiles_prod.sqlite3-wal:/app/db/profiles_prod.sqlite3-wal
      - ./db/profiles_prod.sqlite3-shm:/app/db/profiles_prod.sqlite3-shm
      - ./merged_images:/app/merged_images
      - ./medals:/app/medals
      - ./faceit_elo:/app/faceit_elo
      - ./elo_images:/app/elo_images
      - ./elo_images_rendered:/app/elo_images_rendered
      - ./logs:/app/logs
      - ./translations:/app/translations
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    healthcheck:
      test: ["CMD", "curl", "127.0.0.1:8081"]
      interval: 15s
      timeout: 5s
      retries: 2
      start_period: 30s
    environment:
      - TZ=Europe/Berlin
    networks:
      - monitoring
networks:
  monitoring:
    name: monitoring
    external: true
